{
 "title": "Datathon - API & LLM Observability",
 "tags": [
  "mlops",
  "fastapi"
 ],
 "refresh": "5s",
 "panels": [
  {
   "title": "Requisições em Andamento (Em Tempo Real)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sum(http_requests_in_progress)" }
   ]
  },
  {
   "title": "Total de Requisições Processadas",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "targets": [
    { "expr": "sum(http_requests_total)" }
   ]
  },
  {
   "title": "Taxa de Sucesso vs Erro (Status HTTP)",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status) (http_requests_total{handler=~\"/predict|/chat\"})",
     "legendFormat": "HTTP {{status}}"
    }
   ]
  },
  {
   "title": "Taxa de Requisições por Endpoint (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by (handler) (rate(http_requests_total{handler=~\"/predict|/chat\"}[1m]))",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Latência Média (Segundos)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (handler) (rate(http_request_duration_seconds_sum{handler=~\"/predict|/chat\"}[1m])) / sum by (handler) (rate(http_request_duration_seconds_count{handler=~\"/predict|/chat\"}[1m]))",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Latência - Percentis p80, p90 e p95 (Segundos)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.80, sum by (le, handler) (rate(http_request_duration_seconds_bucket{handler=~\"/predict|/chat\"}[1m])))",
     "legendFormat": "p80 - {{handler}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le, handler) (rate(http_request_duration_seconds_bucket{handler=~\"/predict|/chat\"}[1m])))",
     "legendFormat": "p90 - {{handler}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le, handler) (rate(http_request_duration_seconds_bucket{handler=~\"/predict|/chat\"}[1m])))",
     "legendFormat": "p95 - {{handler}}"
    }
   ]
  }
 ]
}